import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import localFont from 'next/font/local'
import { BrowserRouter } from 'react-router-dom';
import ReduxProvider from '@/providers/redux';

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})
const myFont = localFont({
  src: 'Poppins-Bold.ttf',
  display: 'swap'
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <PrimeReactProvider>
        <body className={inter.className}>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </body>
      </PrimeReactProvider>
    </html>
  )
}
